/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

package me.khosraw;

import java.util.Arrays;

public class MultiplesOf {

    public static void main(String[] args) {
        int[] multiples = new int[0];

        for (int i = 0; i <= 1000; i++) {
            if (i % 3 == 0 || i % 5 == 0) {
                multiples = Arrays.copyOf(multiples, multiples.length + 1);
                multiples[multiples.length - 1] = i;
            }
        }
        int result = 0;
        for (int i = 0; i < 467; i++) {
            result = result + multiples[i];
        }

        System.out.println(result);
    }
}